# Database settings.
db.url=jdbc:postgresql://localhost:5432/ylabdb
db.username=ylab_user
db.password=ylab_pass

# Liquibase settings.
liquibase.changelog=db.changelog/db.changelog-master.xml
liquibase.defaultSchemaName=domain
liquibase.liquibaseSchemaName=service

# Repository settings.
repo.product=jdbc
repo.user=jdbc
repo.audit=jdbc